version : "3.9"
services:
    postgres-svc:
        image   : postgres
        env_file: .env.docker
        ports   :
            - "5432:5432"
        volumes :
            - amico-backend-data:/var/lib/postgresql/data
    
    adminer-svc:
        image: adminer
        ports:
            - "8080:8080"

volumes :
    amico-backend-data: